/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://whzk2b67t5erxdztlsd7dunw6u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ookwftg4rrg2xm3zqnrc2khwxu",
    "aws_cognito_identity_pool_id": "us-east-1:6476a0a9-8010-4a32-9880-6fe793d035f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cGW8bw3V8",
    "aws_user_pools_web_client_id": "6rhdje4mui9e6qtie1pilj24pe",
    "oauth": {
        "domain": "usd210-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://usd210-requests.vercel.app",
        "redirectSignOut": "https://usd210-requests.vercel.app",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "e2013c375d454dbfbbf5213a42b4e079",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
