/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mlxcqkafdbbphgoiy73t4ql4ue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vtm4aod2zjdnfksz6tmzh32fxm",
    "aws_cognito_identity_pool_id": "us-east-1:0c11fb06-0882-4823-affb-210feeed3e5b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EOf6wBIEU",
    "aws_user_pools_web_client_id": "ucrh91lqne4psuvifb4v6k2gc",
    "oauth": {
        "domain": "usd210-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000",
        "redirectSignOut": "http://localhost:3000",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "fcc4f19c78cd484e90127b4d4920bc9b",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
