/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_mobile_analytics_app_id": "84dd737e990c4e0fa3d441d911c8774a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://o5e6c7ynevg2tcrprdxhxlqmlq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mw5wt2zcqfac5jyvpfucvfjkta",
    "aws_cognito_identity_pool_id": "us-east-1:6476a0a9-8010-4a32-9880-6fe793d035f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cGW8bw3V8",
    "aws_user_pools_web_client_id": "6rhdje4mui9e6qtie1pilj24pe",
    "oauth": {
        "domain": "usd210-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000",
        "redirectSignOut": "http://localhost:3000",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
